name: My First Workflow for Learning
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
      - run: echo "Hello World"
